class kablamo::cpanmodules {
    cpanm { 'App::Ack':                            }
    cpanm { 'App::Genpass':                        }
    cpanm { 'App::Uni':                            }
    cpanm { 'App::cpanoutdated':                   }
    cpanm { 'App::mymeta_requires':                }
    cpanm { 'Authen::Passphrase':                  }
    cpanm { 'Bundle::LWP':                         }
    cpanm { 'CEDict::Pinyin':                      }
    cpanm { 'Captcha::reCAPTCHA':                  }
    cpanm { 'Capture::Tiny':                       }
    cpanm { 'Carp::Always':                        }
    cpanm { 'Catalyst::Devel':                     }
    cpanm { 'Catalyst::Manual':                    }
    cpanm { 'Catalyst::Plugin::Assets':            }
    cpanm { 'Catalyst::Plugin::Cache::HTTP':       }
    cpanm { 'Catalyst::Plugin::Compress::Gzip':    }
    cpanm { 'Catalyst::Plugin::Log::Dispatch':     }
    cpanm { 'Catalyst::Plugin::StackTrace':        }
    cpanm { 'Catalyst::Plugin::Unicode::Encoding': }
    cpanm { 'Catalyst::View::JSON':                }
    cpanm { 'Catalyst::View::TT':                  }
    cpanm { 'CatalystX::AuthenCookie':             }
    cpanm { 'DBD::SQLite':                         }
    cpanm { 'DBI':                                 }
    cpanm { 'Data::Currency':                      }
    cpanm { 'Data::Dumper::Concise':               }
    cpanm { 'Data::Printer':                       }
    cpanm { 'Data::TreeDumper':                    }
    cpanm { 'DateTime':                            }
    cpanm { 'DateTime::Format::SQLite':            }
    cpanm { 'Devel::REPL':                         }
    cpanm { 'Dist::Zilla':                         }
    cpanm { 'Dist::Zilla::PluginBundle::DAGOLDEN': }
    cpanm { 'Fey':                                 }
    cpanm { 'Fey::Loader':                         }
    cpanm { 'Fey::ORM':                            }
    cpanm { 'Git::Wrapper':                        }
    cpanm { 'HTML::Scrubber':                      }
    cpanm { 'HTTP::Tiny':                          }
    cpanm { 'IO::CaptureOutput':                   }
    cpanm { 'IO::Socket::SSL':                     }
    cpanm { 'IPC::Run3':                           }
    cpanm { 'IPC::System::Simple':                 }
    cpanm { 'Image::ExifTool':                     }
    cpanm { 'JSON::XS':                            }
    cpanm { 'LWP::Protocol::https':                }
    cpanm { 'List::AllUtils':                      }
    cpanm { 'Log::Dispatch::Config':               }
    cpanm { 'Math::Random::MT':                    }
    cpanm { 'Module::Load::Conditional':           }
    cpanm { 'Moose':                               }
    cpanm { 'MooseX::Getopt::Usage':               }
    cpanm { 'Net::Server::SS::PreFork':            }
    cpanm { 'Number::Format':                      }
    cpanm { 'Path::Class':                         }
    cpanm { 'Path::Class::Rule':                   }
    cpanm { 'Plack':                               }
    cpanm { 'Plack::Middleware::Assets':           }
    cpanm { 'Pod::Cpandoc':                        }
    cpanm { 'Regexp::Common':                      }
    cpanm { 'Server::Starter':                     }
    cpanm { 'Syntax::Keyword::Junction':           }
    cpanm { 'Test::Most':                          }
    cpanm { 'Test::Routine':                       }
    cpanm { 'Text::CSV':                           }
    cpanm { 'Time::HiRes':                         }
    cpanm { 'URI':                                 }
    cpanm { 'Vi::QuickFix':                        }
    cpanm { 'WWW::Mechanize':                      }
    cpanm { 'YAML::XS':                            }

}
